name: Unit tests
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python: ['3.7', '3.8']
        os: ['ubuntu-latest']
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          pip install flake8
          # Stop the build if there are Python syntax errors or undefined names.
          flake8 . --select=E9,F63,F7,F82 --show-source
          # Exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide.
          flake8 . --exit-zero --max-complexity=10 --max-line-length=127
      - name: Run unit tests
        run: |
          python -m unittest discover -v tests/
        env:
          AUTOMX2_CONF: 'tests/unittest.conf'
          RUN_LDAP_TESTS: 0
